### ISSUE TITLE
requirements.txt not found and package odl seems having updated.

### ISSUE THREAD

**Issue by NGA-MMDDsteven** [hongwang01/InDuDoNet#3]
Can you provide requirements.txt? My pytorch version is 1.6.0, whose level seems too high for the repo.

Besides, I install odl in command : pip install odl

The function of odl seems having changed! Such as odl.tomo.FanBeamGeometry has changed to odl.tomo.FanFlatGeometry and odl_torch.OperatorModule has changed to odl_torch.OperatorAsModule.

I'm not sure the change is correct, please check!

**Comment by NGA-MMDDsteven** [comment]
I changed my pytorch version from 1.6.0 to 1.0.0.
I have another error :

**RuntimeError: could not compute gradients for some functions**

**Comment by NGA-MMDDsteven** [comment]
> I changed my pytorch version from 1.6.0 to 1.0.0. I have another error :
> 
> **RuntimeError: could not compute gradients for some functions**

I uninstall the odl and build the odl source file. Now the training is working!

`git clone https://github.com/odlgroup/odl`
`cd odl`
`pip install --user --editable .`

我觉得这个可以适当的在readme里面补充一下，还有就是开头提到的requirements.txt文件。

**Comment by hongwang01** [comment]
> Can you provide requirements.txt? My pytorch version is 1.6.0, whose level seems too high for the repo.
> 
> Besides, I install odl in command : pip install odl
> 
> The function of odl seems having changed! Such as odl.tomo.FanBeamGeometry has changed to odl.tomo.FanFlatGeometry and odl_torch.OperatorModule has changed to odl_torch.OperatorAsModule.
> 
> I'm not sure the change is correct, please check!



> Can you provide requirements.txt? My pytorch version is 1.6.0, whose level seems too high for the repo.
> 
> Besides, I install odl in command : pip install odl
> 
> The function of odl seems having changed! Such as odl.tomo.FanBeamGeometry has changed to odl.tomo.FanFlatGeometry and odl_torch.OperatorModule has changed to odl_torch.OperatorAsModule.
> 
> I'm not sure the change is correct, please check!

First， thank you for your interest in our work !

Sorry for the missing. We have added the requirements.txt in our repo. Thanks!

For the installation of ODL, we have downloaded the repo from https://github.com/odlgroup/odl and then pip install.

**Comment by hongwang01** [comment]
> I changed my pytorch version from 1.6.0 to 1.0.0. I have another error :
> 
> **RuntimeError: could not compute gradients for some functions**

Please first check whether you have installed the packages correctly.

**Comment by hongwang01** [comment]
> > I changed my pytorch version from 1.6.0 to 1.0.0. I have another error :
> > **RuntimeError: could not compute gradients for some functions**
> 
> I uninstall the odl and build the odl source file. Now the training is working!
> 
> `git clone https://github.com/odlgroup/odl` `cd odl` `pip install --user --editable .`
> 
> 我觉得这个可以适当的在readme里面补充一下，还有就是开头提到的requirements.txt文件。

谢谢您的提议，也感谢您对我们工作的关注，我们已经在repo中做了对应的注释。
